### ISSUE TITLE
FeatureRequest: wifi search should be only executed by the user request (open settings page)

### ISSUE THREAD

**Issue by LukeTheMast3r** [ohAnd/dtuGateway#20]
Hi Andreas,

after looking into serial terminal i saw that the device searches for wifi's again and again even if its conected to one.

Only for my understanding: Is that necessary? e.g. for keeping the wifi alife?
Wouldn't it be nice to search the Wifi only when not connected? or when the settings page gets opened?

Have a nice Evening
Lukas

**Comment by ohAnd** [comment]
Yes, that's right ;-)

Since _1.5.0034_develop_ that function will called only in background to update the environment, so it not consumes cpu time. That's currently the easiest thing to meet different (not known) use cases for the usabilty.

And also yes, could be updated only with some wait time, when the settings page is opened - with some extra effort on dev side...

We can put it on the backlog.
