### ISSUE TITLE
Mobile Browser show raw html code (fw version: 1.6.0008)

### ISSUE THREAD

**Issue by steffengoethling** [ohAnd/dtuGateway#39]
When i open the dtu surface on my mobile phone, i see the raw html code instead the rendered dtu gateway surface

**To Reproduce**
1. Go to dtu home with iPhone mobile browser (Safari, Chrome)
2. See raw html code

**Expected behavior**
Normal surface is shown

**Screenshots**
![dtugateway home](https://github.com/user-attachments/assets/8d4810ff-b1d7-494c-b2e3-3f31461fc224)

**Smartphone (please complete the following information):**
 - iPhone 14
 - OS: 17.5.1
 - Browser safari, chrome
 - Version newest

**Comment by ohAnd** [comment]
Hi @steffengoethling ,

thanks for the hint ... that's weird.
I don't checked for every snapshot / release iOS based systems. (with earlier versions it definitely works)
But at least for this version, the website will be not rendered on iOS based devices (checked on iPhone/iPad) neither with safari nor with edge.
On windows with chrome/ edge/ firefox and also an a chromebook with chrome there are no issues...

Due to the upcoming change to the 2.x path of dtuGateway, maybe you want to directly change to the new path (branch: [migrate_ESP32](https://github.com/ohAnd/dtuGateway/tree/migrate_ESP32)) - that problem is not given here.

Or try some of the older releases to start.

I will check with delay what could be the problem here...

BR

**Comment by steffengoethling** [comment]
Hey BR,

yes, with the older release the surface is shown on my iPhone. On my MacBook is everything normal with Chrome and the actual release. I don't want to downgrade, because i want use the new power limit functionality :-)
Thank you very much for your support and for sharing the software!

Best regards

Steffen
